export const SET_ACTIONS = 'LIST/SET_ACTIONS';
export const CONCAT_ACTIONS = 'LIST/CONCAT_ACTIONS';
export const CLEAR_ACTIONS = 'LiIST/CLEAR_ACTIONS';
export const CREATE_ACTION = 'LIST/CREATE_ACTION';
